version: "3"
services:
  app:
    build: .
    environment:
      - BOT_TOKEN=
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 192.168.21.10
      
  db:
    image: mysql
    ports:
      - "32000:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      app_net:
        ipv4_address: 192.168.21.11
        
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.21.0/24"
 