version: "3"
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=ODM0MDUxODYzODg3MjE2NjQw.YH7RVA.52tgMolwyzniCd1qrUIZ19qm5qo
    depends_on:
      - bot_db
    networks:
      bot_net:
        ipv4_address: 192.168.21.10
      
  bot_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      bot_net:
        ipv4_address: 192.168.21.11
        
networks:
  bot_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.21.0/24"
 
